server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://prod-db:3306/estoque_prod?useSSL=false&serverTimezone=UTC
    username: prod_user
    password: prod_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    mongodb:
      uri: mongodb+srv://usuario:senha@cluster0.mongodb.net/estoque_prod_mongo?retryWrites=true&w=majority
